import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-neutral-900 dark:text-white flex flex-col h-screen`}
      >
        <h1 className="w-full p-4 text-3xl font-semibold sticky top-0 bg-gray-700 dark:bg-neutral-950 text-white shrink-0">
            Rust Scout Bot
        </h1>
        <div className="w-full grow flex justify-center">
            {children}
        </div>
      </body>
    </html>
  );
}
